DECLARE @BACKUP_FILE AS VARCHAR(200) = FORMAT(GETDATE(),'yyyyMMdd_hhmm') + '.bak' 
DECLARE @DISK AS VARCHAR(500) =  'D:\Projects\ST\BACKUPS\ST_' + @BACKUP_FILE
BACKUP DATABASE [ST] 
TO  DISK = @DISK
WITH NOFORMAT, INIT,  NAME = N'Service Tracker-Full Database Backup', SKIP, NOREWIND, NOUNLOAD, COMPRESSION,  STATS = 10

ALTER DATABASE [ST_TEST] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [ST_TEST] 
	FROM  
	DISK = @DISK
	WITH  FILE = 1,  
	MOVE N'ST_Data' TO N'D:\Avocet\DATABASES\ST_TEST.mdf',  
	MOVE N'ST_Log' TO N'D:\Avocet\DATABASES\ST_TEST.ldf',  
	NOUNLOAD,  
	REPLACE,  
	STATS = 5
ALTER DATABASE [ST_TEST] SET MULTI_USER
GO
