USE Avocet_Geothermal_Test
GO
DECLARE @AT AS DATETIME = '20180101'
DECLARE @SRC AS VARCHAR(32) = 'Avocet_Geothermal'
DECLARE @TGT AS VARCHAR(32) = 'Avocet_Geothermal_Test'
DECLARE @AT_STR AS VARCHAR(30) = CAST(@AT AS VARCHAR(30))
DECLARE @TBL TABLE 
(
	TABLENAME VARCHAR(50)
	,DELQUERY NVARCHAR(MAX)
)
DELETE  FROM Avocet_Geothermal_Test.dbo.ITEM_BLOB_STORE WHERE BLOB_ID IN (SELECT BLOB_ID FROM Avocet_Geothermal_Test.dbo.IE_PROC_GRP_LOG WHERE BLOB_ID IS NOT NULL UNION SELECT BLOB_ID BLOB FROM Avocet_Geothermal_Test.dbo.IE_PROC_LOG_HDR WHERE BLOB_ID IS NOT NULL)
DELETE  FROM Avocet_Geothermal_Test.dbo.ITEM_BLOB_STORE WHERE BLOB_ID IN (SELECT BLOB_ID FROM Avocet_Geothermal_Test.dbo.IE_PROC_GRP_LOG WHERE BLOB_ID IS NOT NULL UNION SELECT BLOB_ID BLOB FROM Avocet_Geothermal_Test.dbo.IE_PROC_LOG_HDR WHERE BLOB_ID IS NOT NULL)

INSERT INTO @TBL SELECT 
	TYPE
	,'TRUNCATE TABLE ' +  @TGT + '.dbo.' + PROP_TBL_NAME 
FROM Avocet_Geothermal.dbo.TYPE WHERE PROP_TBL_NAME IN
(
	'WISKI_HF_DATA'
	,'LOG_ROWS'
	,'BHDATA_DEPTH'
	,'IE_PROC_GRP_LG_RF'
	,'IE_PROC_GRP_LOG'
	,'IE_PROC_LOG_HDR'
	,'IE_PROC_LOG_REF'
	,'IE_PROCESS_LOG'
)


INSERT INTO @TBL SELECT 
	TYPE
	,'DELETE ' +  @TGT + '.dbo.' + PROP_TBL_NAME + ' WHERE EVENT_TYPE = ''' + TYPE + ''' AND START_DATETIME < ''' +@AT_STR  + ''''  
FROM Avocet_Geothermal.dbo.TYPE WHERE TYPE_CLASS = 'TRANSACTION'



DECLARE @TABLENAME  AS VARCHAR(MAX)
DECLARE @DELQUERY  AS VARCHAR(MAX)
DECLARE CUR CURSOR FOR SELECT TABLENAME, DELQUERY FROM @TBL
OPEN CUR
FETCH NEXT FROM CUR INTO @TABLENAME, @DELQUERY
WHILE @@FETCH_STATUS = 0 
BEGIN
	PRINT('------MIGRATING------'	+ @TABLENAME)
	PRINT '\tDELETE QUERY: '  + @DELQUERY
	BEGIN TRY
		EXEC(@DELQUERY)
		DECLARE @FOO INT
	END TRY
	BEGIN CATCH
		PRINT('------ERROR MIGRATING------'	+ @TABLENAME)
		PRINT ('ERROR:' + ERROR_MESSAGE())
		PRINT '\tDELETE QUERY: '  + @DELQUERY
	END CATCH
	PRINT('------DONE------')
	FETCH NEXT FROM CUR INTO @TABLENAME, @DELQUERY
END
CLOSE CUR
DEALLOCATE CUR



 