USE [master]
ALTER DATABASE [ST_TEST] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
RESTORE DATABASE [ST_TEST] 
	FROM  
	DISK = @DISK
	WITH  FILE = 1,  
	MOVE N'ST_Data' TO N'D:\Avocet\DATABASES\ST_TEST.mdf',  
	MOVE N'ST_Log' TO N'D:\Avocet\DATABASES\ST_TEST.ldf',  
	NOUNLOAD,  
	REPLACE,  
	STATS = 5
ALTER DATABASE [ST_TEST] SET MULTI_USER
GO


